- name: ALL variables
  hosts: local
  connection: local
  vars: 
    course: ansible
    duration: 10hrs
  vars_prompt:
    - name : course
      prompt: What is course
      private: false
  vars_files:
    - course.yaml
  tasks:
    - name: Testing prefernce 
      vars:
        name: course
      ansible.builtin.debug:
        msg: "course is :{{ course }}"