- name: Using facts
  hosts: local
  connection: local
  become: yes
  tasks:
    - name:  install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
    - name:  install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debain"

