- name: install Packages
  hosts: local
  connection: local
  tasks:
    - name: packages
      ansible.builtin.Package:
        name: "{{ item }}"
        state: present
      loop:
      - nginx
      - mysql
      - zip
      - nodejs