- name: INstall and remove packages
  hosts: local
  connection: local
  tasks:
    - name: install and remove
      ansible.builtin.package:
        name: "{{ item.name }}" 
        state: "{{ ietm.state }}"
      loop:
      - { name: "mysql",state: "absent"}
      - { name: "nodejs",state: "latest"}
     