- name: Functions
  hosts: local
  connection: local
  vars:
    technologies: devops,aws,shell,ansible
    name: "Poojith kumar p"
    gmail: "poojithkumar.p123@gmail.com"
    ipaddres: "19222.168.0.1"
    tags:
      Application: payment
      Environment: dev
    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
    - name: string to list
      ansible.builtin.debug:
        msg: "List: {{ technologies | split(',') }}"

    - name: map to list
      ansible.builtin.debug:
        msg: "list: {{ tags | dict2items }}"

    - name: List into map
      ansible.builtin.debug:
        msg: "Map: {{ listTags | items2dict }}"
  
    - name: read yaml to the variable
      ansible.builtin.set_fact:
        student_yaml=" {{ lookup('file','student.yaml'| from_yaml)}}"

    - name: yaml to json
      ansible.builtin.debug:
        msg: "JSon; {{ student_yaml | to_json }}"

    - name: json to file
      ansible.builtin.copy:
        dest: ./student-json.yaml
        content: "{{ student_yaml | to_json }}"

    - name: convert into uppercase
      ansible.builtin.debug:
        msg: " {{ name | upper }}"

    - name: convert into lower
      ansible.builtin.debug:
        msg: "{{ gmail | lower }}"
    
    - name: check ipaddress are  not 
      ansible.builtin.debug:
       msg: "{{ ipaddres | ansible.utils.ipv4}}"

    - name: grep root
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: command_output

    - name: print command output
      ansible.builtin.debug:
        msg: " {{ command_output }}"


    

