- name: Functions
  hosts: local
  connection: local
  vars:
    technologies: devops,aws,shell,ansible
  tags:
      Application: payment
      Environment: dev

    
   
  tasks: 
    - name: Default variable
      ansible.builtin.debug:
        msg: "Hello {{ name | default('poojith') }}"
    
    - name: string to list
      ansible.builtin.debug:
        msg: "The list is : {{ technologies | split(',') }}"

    - name: map to list
      ansible.builtin.debug:
        msg: "The list is : {{ tags | dict2items }}"
  
  


    

